### ISSUE TITLE
Support for AudioStream?

### ISSUE THREAD

**Issue by swiftcoder** [NiklasEi/bevy_kira_audio#10]
For generative and/or streaming audio, supporting playing the AudioStream type directly would be extremely useful.

This would be analogous to [AudioManager.add_stream()](https://docs.rs/kira/0.5.2/kira/manager/struct.AudioManager.html#method.add_stream).

Here's a [simple example of using AudioStream](https://gist.github.com/swiftcoder/522c202a2d6f5bd6d2b00abdb2473575) for generative audio.

**Comment by NiklasEi** [comment]
Closed in #11 

Version 0.5 published on cretes.io includes it
