### ISSUE TITLE
Channel settings overridden by individual sound settings

### ISSUE THREAD

**Issue by Zakru** [NiklasEi/bevy_kira_audio#103]
I expect that setting, for example, a channel's volume to 0.5 and playing a sound on it with volume 0.5 results in the sound playing at a volume of 0.5 * 0.5 = 0.25. Instead, manually setting a sound's settings overrides the channel's.

If this is intended behavior, I think it is worth at least documenting, but it would be a nice convenience to be able to set, for example, the music and SFX channel volumes in just one place, and then set the individual sound volumes without worrying about the entire channel's volume.

Context: we're using custom attenuation/spatialization/occlusion, so we have to update volumes and panning every frame.

**Comment by Selene-Amanita** [comment]
At the very least it should be possible to get the volume of the channel (maybe it is and I missed something?).

**Comment by NiklasEi** [comment]
I agree, thanks for raising the issue
