### ISSUE TITLE
Create paused `AudioInstance`

### ISSUE THREAD

**Issue by ickk** [NiklasEi/bevy_kira_audio#105]
I am using a pattern where we create a looping sound at the same time that our entity gets created. The sound is intended to loop, but should not play immediately (think jet noise, on an initially stationary vehicle). 

```rust
let handle = channel.play(my_sound.clone()).looped().handle();
```

We currently use something analogous to the code above to create the `AudioInstance`, and what happens is the channel plays sound for one frame, and then we are able to pause it on the following frame.

We have tried to get the Instance from `<Assets<AudioInstance>>` in the same system, so that we could immediately call `instance.pause()` however this fails to find the instance.

Is there an alternative pattern that I should be using here?

**Comment by NiklasEi** [comment]
The only way this is currently possible through is pausing the channel before playing or setting the playback speed to 0.

I will add a new method `paused()`, so that your code snippet can become
```rust
let handle = channel.play(my_sound.clone()).looped().paused().handle();
```
