### ISSUE TITLE
Spatial audio volume does not respect the channel's volume

### ISSUE THREAD

**Issue by Skippeh** [NiklasEi/bevy_kira_audio#116]
There's no way to scale the volume of a sound coming from an emitter.

I've linked the relevant line of code that needs to be updated if i understand it correctly.

https://github.com/NiklasEi/bevy_kira_audio/blob/main/src/spacial.rs#L44

**Comment by NiklasEi** [comment]
The whole API is likely to change with #114 due to a switch to a more ECS-centric way of controlling audio.
