### ISSUE TITLE
Playing one shot with spacial audio requires setting volume to 0 on play

### ISSUE THREAD

**Issue by 00alia00** [NiklasEi/bevy_kira_audio#119]
Hiya!
Not sure if this is a known issue or not but I was trying to get spacial audio to work with non looping sounds and noticed that it my sound was still audible even though the listener was far from the emitter.  My hack to fix this is to set all the one shot sounds to 0 volume when I play them.  I think we might need a layer of volume setting specifically for the spacial audio since one might want to tune the volumes relative to each other.. As far as I can tell its currently setting the absolute volume of the sound.

```
  // play the sound
  emitter
    .instances
    .push(audio.play(oneshot.0.clone()).with_volume(0.0).handle());

```

**Comment by RobWalt** [comment]
I can't confirm this. I set the `cooking` sound in the `spatial` example in the repository to be non-looping and it works fine. Can you post some code to reproduce your problem please? Also, what is the value of the `SpatialAudio` resource you're using?

**Comment by NiklasEi** [comment]
This should have been fixed a while ago.
