### ISSUE TITLE
Spatial is spelled wrong in code and examples

### ISSUE THREAD

**Issue by mgi388** [NiklasEi/bevy_kira_audio#120]
I just tried out the spatial stuff and it worked great, thanks!

Small nit: I noticed that things are spelled "spacial" but I believe it should be "spatial" (see https://en.wikipedia.org/wiki/Spatial).

Happy to do a PR for this myself but wanted to raise an issue first to gauge interest.

Thanks for reading my nit issue 😅

**Comment by NiklasEi** [comment]
Oh yeah, that should definitely be fixed :sweat_smile:
