### ISSUE TITLE
Using latest commit for bevy_main branch

### ISSUE THREAD

**Issue by billyb2** [NiklasEi/bevy_kira_audio#13]
Would it be alright if the bevy_main branch of this library just always tracked the latest git commit (`bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }`). It would make it easier for those of use who also keep track of the latest Bevy git commit, instead of having to use a specific revision (as typically, you want to follow the development branch of Bevy since you wan't the latest features all the time).

**Comment by NiklasEi** [comment]
I am honestly not sure about this. Personally, I prefer to update (read: get breaking changes) when I want to and not whenever I compile the next time after commits were pushed to Bevy.
If we do the proposed change, there can be times the `bevy_maser` branch does not compile. I would prefer having it compile at all times and would accept being behind a few commits now and then.

**Comment by billyb2** [comment]
I see where you're coming from. The only (admittedly minor) issue for me is having to recompile all of Bevy twice whenever I use the repo. Could we maybe have two branches that are identical, with the difference being that one follows the latest Bevy always, while the other always follows a stable version of Bevy git (perhaps by renaming bevy_main to bevy_main_stable and then having a bevy_main branch that truly follows it). If not by the way, that's completely fine.

**Comment by NiklasEi** [comment]
Since I don't think this is the working mode of many users, I'd prefer to keep this in forks.

If there are more people commenting here, that they would like such a branch, we can of course talk about it again.

**Comment by billyb2** [comment]
Alright, that's totally fine. Thank you for considering!
