### ISSUE TITLE
Android high latency

### ISSUE THREAD

**Issue by kraftwer1** [NiklasEi/bevy_kira_audio#132]
I'm playing a short sound effect on touch. It plays immediately on iOS, but has a noticable lag on Android (I estimate around 300ms). The same happens using the default Bevy audio (which uses `rodio` I believe). I've seen that there might be a way to fiddle around with buffer sizes in `kira`, see: https://docs.rs/kira/latest/kira/manager/backend/cpal/struct.CpalBackendSettings.html#structfield.buffer_size. The page even mentions that _"the default buffer size might be surprisingly large, leading to latency issues"_. (It seems this is even being discussed on Bevy: https://github.com/bevyengine/bevy/issues/13876).

However I'm not sure how to access those settings from within Bevy or the plugin.

Or there might be other solutions as well? Do you have any tips or hints?

Possibly related: https://github.com/NiklasEi/bevy_kira_audio/issues/79

**Comment by NiklasEi** [comment]
Have you tried patching cpal with https://github.com/RustAudio/cpal/compare/master...Rodrigodd:cpal:oboe-low-latency from the issue above?
