### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by NiklasEi** [NiklasEi/bevy_kira_audio#16]
Following bevyengine/bevy#2373 I would like to adapt licensing of this plugin to keep maximal compatibility with Bevy. For other reasons to switch to MIT/Apache 2.0 please take a look at the Bevy issue.

With only two other contributors this should be much easier than for Bevy itself :wink: 

@rparrett and @CleanCut, I think you know the drill: please comment on this issue with
```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
```

Thanks again for your help!

**Comment by rparrett** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by CleanCut** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by CleanCut** [comment]
Now I'm quite happy I started with MIT+Apache-2.0 on my projects for the last couple years. 😄

**Comment by NiklasEi** [comment]
For completeness: 
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by cryscan** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by billyb2** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.
