### ISSUE TITLE
Build error with latest bevy

### ISSUE THREAD

**Issue by djeedai** [NiklasEi/bevy_kira_audio#25]
Hi-

I'm trying to consume [bevy](https://github.com/bevyengine/bevy) directly from git, due to the fact the latest release 0.5.0 is 6 months old and is missing a few fixes I need (see bevyengine/bevy#2940). However I'm facing many build errors:

```
error[E0432]: unresolved import `bevy::prelude::AppBuilder`
error[E0432]: unresolved imports `bevy::core::AsBytes`, `bevy::render::pass::RenderPassDepthStencilAttachmentDescriptor`
error[E0261]: use of undeclared lifetime name `'w`
error[E0261]: use of undeclared lifetime name `'s`
error[E0107]: this struct takes 2 lifetime arguments but 1 lifetime argument was supplied
```

So I have a few questions:
- Is `bevy_kira_audio` only supposed to work with `bevy` on released version?
- Would it be possible to add some CI to catch those build issues along the way?

Thanks!

**Comment by NiklasEi** [comment]
Are you using the `bevy_main` branch? The main branch is only compatible with the latest release.

I try to keep the commit that `bevy_main` depends on up to date, but it's very likely outdated again.

**Comment by NiklasEi** [comment]
I'll close this since the original issue seems to be resolved.
