### ISSUE TITLE
Update to Bevy 0.6.1

### ISSUE THREAD

**Issue by undersquire** [NiklasEi/bevy_kira_audio#35]
With the latest release of Rust 1.59, Bevy 0.6 and older no longer compile. This prevents the usage of bevy_kira_audio with latest Bevy & Rust.

**Comment by NiklasEi** [comment]
Fixed with `cargo update`?

**Comment by undersquire** [comment]
Not for me no, however others have said that it worked for them. I think something is wrong with my project, I still haven't figured it out.
