### ISSUE TITLE
Slow loading speed in debug

### ISSUE THREAD

**Issue by djeedai** [NiklasEi/bevy_kira_audio#36]
I've observed on Desktop PC with a powerful dev machine that loading a ~3 minute ~6 MiB `.ogg` file takes something like 20+ seconds to be ready to play. Even a 6 MiB `.wav` (so no decompression work) takes several seconds. This means I have to go to great length with preloading and UX delays to hide this loading time to make sure the music is ready to play when the game starts. Given the file sizes, I'd expect both cases to be sub-second loading and decoding.

I appreciate there are good chances this is due to Kira itself and not this binding, but I just wanted to confirm it and see if someone else observed this maybe? I can log an issue with Kira directly if needed. Thanks!

Alternatively, do you know if there is a way to stream while loading maybe?

**Comment by djeedai** [comment]
Oooh interesting, I was adding a Release pipeline and testing my build, and building in release makes the loading almost instantaneous! So it's an issue with Debug builds only; probably something being done in Debug that's overwhelmingly slow?

**Comment by NiklasEi** [comment]
I remember very similar behaviour for images in Bevy (`image` crate). If you want faster loading in debug mode maybe you can optimize some dependencies in the debug profile?

Filing a Kira ticket for this doesn't make any sense at the moment. Kira version `0.6` is in beta and changed the underlying library for `.ogg` decoding from `lewton` to `symphonia`. Updating this plugin to Kira `0.6` might already change the loading speed.

**Comment by NiklasEi** [comment]
I'll close this for now. If you think that there is anything I can do in this crate to improve loading speeds feel free to open a new issue.
