### ISSUE TITLE
Instance handles for Streams

### ISSUE THREAD

**Issue by asafigan** [NiklasEi/bevy_kira_audio#38]
I see that there are Instance handles for sound tracks but not for Streams. Is there a reason for this? it would be nice for example to play multiple streams on a single change and be able to control each one separately. 

I would be willing to work on this if it is as simple as replicating the functionality from the normal audio interface.

**Comment by NiklasEi** [comment]
The soundtrack instance handles do not give any additional control. They enable you to check the playback state of the track.

Control is what channels are for. Is there a reason you do not want to play your two streams in separate channels?

**Comment by asafigan** [comment]
It seems odd not to have control over individual tracks and streams. 

For me, I would like to use one music channel and one sound effects channel so that the player can change there volumes individually. But if I need to be able to stop a sound effect half way through than I have to keep track of all the sound effect settings myself and create a new channel for each instance of a sound effect. I would probably want to have a sound effect pool tracking which of these channels are being used and which aren't. 

This seems like a lot of work for a user of this library to have to implement just for a pretty simple feature. I feel like it would be better if you could have control over individual tracks and use channels for broader effects. I feel instance handles would be a great way to achieve this.

**Comment by NiklasEi** [comment]
Streams, as previously supported, were removed when the plugin was updated to Kira 0.6.

Supporting audio streams for the new Kira version is part of #63
