### ISSUE TITLE
Audio doesn't work in Chrome

### ISSUE THREAD

**Issue by rparrett** [NiklasEi/bevy_kira_audio#4]
Seemingly due to Chrome's restrictions on audio autoplay.

Just in case I never get back around to working on this, I figured I'd dump everything I know about the situation somewhere more durable/googleable than discord.

When starting up a `bevy` project with `bevy_kira_audio`, this shows up in the console:

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
```

I've attempted the workaround described here:

https://developers.google.com/web/updates/2018/11/web-audio-autoplay#moving-forward

Where `AudioContext` is proxied and resumed upon interaction with the page, but that doesn't seem to work. The workaround not working seems like it could be an issue with `cpal` or `kira`. I'm not sure though.

I suppose I could work around this with some sort of "click to start loading the game" button in js/html, but the wasm package  and the assets are large enough that I'd really prefer to have everything loading when the user hits the page.

Another workaround that I'm fine with for my particular application is delaying `bevy_kira_audio`'s creation of the `AudioOutput` until after the user has clicked on something in-game.

I've implemented this here: https://github.com/rparrett/bevy_kira_audio/commit/76b267887a0d65013e5b1f0f4b28056690daa323 

This allows you to
```rs
app.insert_resource(AudioInitialization::new(false));
app.add_plugin(AudioPlugin)
```
And then later on
```
commands.insert_resource(AudioInitialization::new(true));
```

And well, it's not much to look at, but it works.

I'd be happy to open a PR against the `bevy 0.4` tracking branch if desired, but this doesn't seem like particularly useful code outside of working around what seems to be an issue with `cpal`. Just thought I'd add a link here for anyone else experiencing the issue.

edit:
A slightly less wacky API for doing (what I did above) is might be something like

```
app.add_plugin(AudioPlugin { initialize: false })
// ...
fn some_system(audio_init: ResMut<AudioInitialization>) {
    audio_init.needed = true;
}
```

**Comment by zicklag** [comment]
Hey, thanks for the Chrome link! I'm not sure why it didn't work for you, but it worked for me. Here's my `index.html` if it helps:

```html
<html>
  <head>
    <meta charset="UTF-8" />
    <style>
      body {
        margin: 0;
        background-color: black;
      }
      canvas {
        background-color: black;
        /*
          This is a workaround for high DPI screens which winit or something
          has an issue with where it will resize the canvas to smaller than
          the full width of the screen.
        */
        width: 100vw !important;
        height: 100vh !important;
      }
    </style>
  </head>
  <script>
    // Insert hack to make sound autoplay on Chrome as soon as the user interacts with the tab:
    // https://developers.google.com/web/updates/2018/11/web-audio-autoplay#moving-forward
    (function () {
      // An array of all contexts to resume on the page
      const audioContextList = [];

      // An array of various user interaction events we should listen for
      const userInputEventNames = [
        "click",
        "contextmenu",
        "auxclick",
        "dblclick",
        "mousedown",
        "mouseup",
        "pointerup",
        "touchend",
        "keydown",
        "keyup",
      ];

      // A proxy object to intercept AudioContexts and
      // add them to the array for tracking and resuming later
      self.AudioContext = new Proxy(self.AudioContext, {
        construct(target, args) {
          const result = new target(...args);
          audioContextList.push(result);
          return result;
        },
      });

      // To resume all AudioContexts being tracked
      function resumeAllContexts(event) {
        let count = 0;

        audioContextList.forEach((context) => {
          if (context.state !== "running") {
            context.resume();
          } else {
            count++;
          }
        });

        // If all the AudioContexts have now resumed then we
        // unbind all the event listeners from the page to prevent
        // unnecessary resume attempts
        if (count == audioContextList.length) {
          userInputEventNames.forEach((eventName) => {
            document.removeEventListener(eventName, resumeAllContexts);
          });
        }
      }

      // We bind the resume function for each user interaction
      // event on the page
      userInputEventNames.forEach((eventName) => {
        document.addEventListener(eventName, resumeAllContexts);
      });
    })();
  </script>
  <script type="module">
    import init from "/skipngo.js";
    init();
  </script>
</html>
```

`skipngo.js` is my WASM-bindgen generated JS file.

**Comment by NiklasEi** [comment]
This is awesome and works without any code changes in the audio plugin, thanks! I will adapt the `index.html` file and consider this issue closed.

**Comment by NiklasEi** [comment]
@rparrett I just now realized, that you already attempted the above-presented solution and found that it did not work for you. Maybe there has been a fix in `cpal` or `Kira`?
I tried the script solution in all my browsers and found that it works great. Could you check again, please?

**Comment by rparrett** [comment]
I think that the way that Zicklag has implemented the javascript workaround (seems identical to how I had done it) has timing issues. That combined with my testing methodology made me think that it wasn't working at all.

If a user interacts with the page before `bevy_kira_audio` initializes, then sound does not work.

However, this slight tweak resolves that issue:

```diff
- if (count == audioContextList.length) {
+ if (count && count == audioContextList.length) {
```

This prevents the workaround from removing its event listeners if the user interacts with the page before bevy's ready.

I suppose I can live with this.

**Comment by NiklasEi** [comment]
Good catch! Also now added that in the `index.html` of `bevy_game_template`.
