### ISSUE TITLE
bevy_kira_audio::audio_output: Failed to setup audio: BuildStreamError(BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_sw_params' failed with error 'EINVAL: Invalid argument'" } })

### ISSUE THREAD

**Issue by yzn-h** [NiklasEi/bevy_kira_audio#42]
runing it on Pop!_OS VERSION="22.04 LTS"
this is the code https://github.com/NiklasEi/bevy_game_template
there is no sound

i think it is because of pulseaudio

**Comment by NiklasEi** [comment]
This looks like a failure to build Kira's AudioManager. That is either a setup or a Kira issue. I have pulseaudio set up, too and everything works fine.
Maybe you can ask for help with Kira directly? But please note, that `bevy_kira_audio` is currently not using the latest Kira version.

**Comment by NiklasEi** [comment]
Can you retry with version 0.10, please? Now, `bevy_kira_audio` is using the latest Kira version again.
`bevy_game_template` is updated already.

**Comment by yzn-h** [comment]
it works :)
