### ISSUE TITLE
Untyped Custom Channels

### ISSUE THREAD

**Issue by cryscan** [NiklasEi/bevy_kira_audio#52]
In 0.10.0 custom channels are distinguished by marker types. It may be hard to utilize a dynamic number of channels at run time. For example, in a game one may want to assign one channel to each collision event to set the volume and pitch accordingly, but they have no idea how many and which channels to be assigned to. In previous versions they only need to use dynamic strings to index these channels, but it's made harder now. Is it possible to have an untyped collection of channels in addition?

**Comment by NiklasEi** [comment]
I am planning to support things like `set_volume` and `set_pitch` on the instance handles, too.
In your use case it would probably be more fitting to have one channel for collision events, but keep a map of collision to instance handle.

**Comment by cryscan** [comment]
I see, thanks!
