### ISSUE TITLE
Unexpected `PlaybackState` behavior

### ISSUE THREAD

**Issue by 5tr1k3r** [NiklasEi/bevy_kira_audio#54]
There are 3 slightly different cases. The common part is that we're playing a short sound on a separate AudioChannel with `play()` method.
- Waiting for the sound to end. Checking PlaybackState: it is permanently `PlaybackState::Playing`
- Waiting for the sound to end, running `stop()` method. Checking PlaybackState: it is permanently `PlaybackState::Playing`
- Not waiting for the sound to end, running `stop()` method while the sound is still playing. Checking PlaybackState: it is permanently `PlaybackState::Stopping`

In all cases my expectation for PlaybackState would be `PlaybackState::Stopped`.

**Comment by hakolao** [comment]
With this library, I can't figure out any way to know my audio has played (to e.g. start another background song after it).

Even the example gives `Playing` status after stopping the channel.

```
Audio stopped.
Loop audio Playing { position: 0.9663492063492064 }
```

I would too expect that a song would turn to `Stopped` after playing in all above cases.

Also, the `PlaybackState::Playing` never reaches the duration (seconds) of the audio in position.

**Comment by NiklasEi** [comment]
Found and fixed a bug concerning the "Stopped" state. The original three cases should now all work as expected on `main`.

**Comment by hakolao** [comment]
That when I compared where the duration as secs f64 of the audio vs the position in playing, it did not stop at the duration, but before.

but I was trying to use the duration comparison only because the state did not go to Stopped. Thst was all I needed.

I don’t know what the expected behavior is regarding that.

@NiklasEi

**Comment by NiklasEi** [comment]
The state gets updated once per frame. Meaning that there can be a time difference of up to the current delta. Kira itself probably also updates on an interval, but I would expect that to be much smaller than a usual frame duration.

I will consider this issue closed then. Feel free to open a new issue if you find the discrepancy of the play time larger than expected.
