### ISSUE TITLE
bevy_master vs bevy_main

### ISSUE THREAD

**Issue by CleanCut** [NiklasEi/bevy_kira_audio#7]
The readme states:

> The branch `bevy_main` is tracking `bevy/main`.

...but there is no `bevy_main` branch.  Perhaps the `bevy_master` branch was meant to be renamed?

<img width="344" alt="image" src="https://user-images.githubusercontent.com/5838512/113810847-5544f280-9728-11eb-9d53-610d19c71f59.png">

**Comment by NiklasEi** [comment]
Yeah, sorry for the confusion. I will delete the `bevy_master` branch since it was already merged in #6.

**Comment by CleanCut** [comment]
Thanks for explaining!  Do you have plans for making a release to target Bevy 0.5.0?

**Comment by NiklasEi** [comment]
The latest release targets Bevy 0.5.0. Is it not working for you?

**Comment by CleanCut** [comment]
Oh! No, I just jumped to the conclusion that bevy_kira_audio 0.4.0 was for Bevy 0.4.0.  I'll go give it a try right now!

**Comment by CleanCut** [comment]
Works great! I opened a PR for a minor issue I hit: https://github.com/NiklasEi/bevy_kira_audio/pull/8
