### ISSUE TITLE
Expose `PlayAudioCommand` type 

### ISSUE THREAD

**Issue by harudagondi** [NiklasEi/bevy_kira_audio#71]
`PlayAudioCommand` can be accessed by using `AudioChannel::play`, but the type is hidden behind the private `audio` module.

Also, this type is not showing up in docs.rs, so to know its methods you have to go to the source code in the repo. You can't even go to the source code through docs.rs.

**Comment by nicopap** [comment]
Strongly agree with this, it makes using the API very hard. I can't even look up the docs for the API I'm intended to use!
