### ISSUE TITLE
Reexport `kira`

### ISSUE THREAD

**Issue by harudagondi** [NiklasEi/bevy_kira_audio#73]
Currently, to create a `StaticSoundData` for `AudioSource`, you have to import `kira` with the correct version. I'd like... to not do that lol.

Also, in the case that #63 would be implemented, it is likely that users would have to reimport `kira` just to implement their own `SoundData`.

A solution to this is to reexport `kira` itself.

**Comment by NiklasEi** [comment]
Not sure about reexporting Kira here. I would prefer to keep the API backend agnostic. For #63 there will likely be a new trait from `bevy_kira_audio`. We could do the same for `StaticSoundData`.
Would that be fine?

**Comment by harudagondi** [comment]
I think reexporting `StaticSoundData`, `SoundData`, and `Sound` would be fine. However, when a new type from kira is used in the public api, then it should also be exported.

Is there a way for Github Actions to know that a foreign item is used, but not reexported?
