### ISSUE TITLE
What is Kira's scope?

### ISSUE THREAD

**Issue by brandon-reinhart** [NiklasEi/bevy_kira_audio#74]
Bevy could use the ability to structure multiple sound operations into a chain similar to a UE cue file. This might be a set of samples, then selecting one randomly, then applying an effects filter. A format would describe a series of functions to be applied to yield the final sound. Gameplay would interact with this high level cue-like format.

Do you envision Kira providing that kind of functionality or do you envision it only provides low level services and the operations level features exist at some higher level?

**Comment by brandon-reinhart** [comment]
Inspiration: https://docs.unrealengine.com/4.27/en-US/WorkingWithAudio/SoundCues/Editor/

**Comment by NiklasEi** [comment]
Maybe you want to ask this on the [Kira](https://github.com/tesselode/kira) project? If we do it here, there would already be the "higher level" solution.
Just be aware, that Kira might already support parts of this. The Bevy plugin does not jet expose most of Kira's functionality.
