### ISSUE TITLE
Random sound selection?

### ISSUE THREAD

**Issue by brandon-reinhart** [NiklasEi/bevy_kira_audio#75]
Let me know if this belongs in Kira instead of here.

I'd like to be able to specify a list of sounds, not just one, and then some strategy (distribution) to select among them. This would be like a cue in UE4 with several sounds (ex: footsteps) and then you select which one you'd like.

I don't want to write code like this:

```
fn load_sounds(asset_server: Res<AssetServer>, mut tile_painter_sfx: ResMut<TilePainterSFX>) {
    // We should add support for selecting among samples.
    // This would be similar to cue files in UE.
    // This should probably change from referencing oggs to rons.
    let place_tile_sfx = vec![
        "audio/effects/dirt_impact/dirt_impact_1.ogg",
        //"audio/effects/dirt_impact/dirt_impact_2.ogg",
        "audio/effects/dirt_impact/dirt_impact_3.ogg",
        //"audio/effects/dirt_impact/dirt_impact_4.ogg",
        "audio/effects/dirt_impact/dirt_impact_5.ogg",
        "audio/effects/dirt_impact/dirt_impact_6.ogg",
        "audio/effects/dirt_impact/dirt_impact_7.ogg",
    ];

    for &sfx in place_tile_sfx.iter() {
        tile_painter_sfx.on_place.push(asset_server.load(sfx));
    }
}

// ...
        let mut rng = rand::thread_rng();
        sfx_event_writer.send(UiPlaySoundEvent {
            source: tile_painter_sfx.on_place[rng.gen_range(0..tile_painter_sfx.on_place.len())]
                .clone(),
        });
// ...
```

I can write the PR, but want to put it in the correct crate and at the correct scope. Suggestions?

**Comment by NiklasEi** [comment]
The way I would currently implement this: keep the handle array in a resource and have a method on the resource struct to get a random handle. This seems like the correct place for this functionalty to me. Do you have a reason why you would like this in the audio plugin?

To make your code example nicer, you could use a plugin like `bevy_asset_loader`.
