### ISSUE TITLE
Support reading 'chunks' from a single audio file

### ISSUE THREAD

**Issue by cBournhonesque** [NiklasEi/bevy_kira_audio#82]
Hi,

Does kira_audio support having a single audio asset, but then having Audio handles that will read only parts of the audio file? (e.g. from 0.8sec to 1.5sec)

This would be helpful for the web as I would like to limit the number of files that clients have to download, so I'd like to 'merge' all audio files into one.

**Comment by NiklasEi** [comment]
You should be able to achieve this using the sound settings. See [playback_region](https://github.com/NiklasEi/bevy_kira_audio/blob/main/assets/sounds/loop_with_settings.ogg.ron#L6C4-L6C4).
