### ISSUE TITLE
Chrome: The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by smessmer** [NiklasEi/bevy_kira_audio#83]
When using this in a game and running it with WASM on a website, I'm seeing this error from Google Chrome:

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.
https://goo.gl/7K7WLu
```

Is there a way for me to resume the audio context after a user gesture? Say I add a button to the website that says "enable audio", that button then calls into my WASM Rust code, and then what? Can the Rust code reinitialize Kira's AudioContext? Or, even better, can I somehow do it fully from JavaScript without having to cross the boundary to Rust?

**Comment by NiklasEi** [comment]
[You can use scripts to restart the audio context on any user interaction](https://developer.chrome.com/blog/web-audio-autoplay/#moving-forward). If you would like to see this used in a bevy project, take a look at [bevy_game_template](https://github.com/NiklasEi/bevy_game_template/blob/main/build/web/sound.js).
Also see #4 

Thanks for bringing this up again. I think the readme should point this out (and I thought it did, but I cannot find that section anymore). I'll update the documentation.

**Comment by smessmer** [comment]
Thanks, that works :)
